services:
  hadoop-master:
    image: hadoop:latest
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"   # NameNode Web UI
      - "8088:8088"   # ResourceManager Web UI
      - "7077:7077"   # Spark Master
      - "19888:19888" # JobHistory Server
      - "8080:8080"   # Spark Master Web UI
      - "9000:9000"   # NameNode RPC
    volumes:
      - ~/Documents/hadoop_project:/shared_volume
    networks:
      - hadoop-network
    environment:
      - HADOOP_OPTS=-XX:-UseContainerSupport
      - YARN_OPTS=-XX:-UseContainerSupport
    stdin_open: true
    tty: true
  hadoop-slave1:
    image: hadoop:latest
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"   # NodeManager Web UI
    networks:
      - hadoop-network
    environment:
      - HADOOP_OPTS=-XX:-UseContainerSupport
      - YARN_OPTS=-XX:-UseContainerSupport
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master
    
  hadoop-slave2:
    image: hadoop:latest
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042"   # NodeManager Web UI
    networks:
      - hadoop-network
    environment:
      - HADOOP_OPTS=-XX:-UseContainerSupport
      - YARN_OPTS=-XX:-UseContainerSupport
    stdin_open: true
    tty: true
    depends_on:
      - hadoop-master
  hive-server:
    image: apache/hive:4.0.0-alpha-2
    container_name: hive-server
    hostname: hive-server
    ports:
      - "10000:10000"  # JDBC port
      - "10002:10002"  # Web UI port
      - "9083:9083"    # Metastore port
    volumes:
      - ./hadoop_project:/shared_volume
    environment:
      - SERVICE_NAME=hiveserver2
    networks:
      - hadoop-network
    tty: true
    stdin_open: true
networks:
  hadoop-network:
    driver: bridge
